const tests = { // these tests are in the original chronolgiacal order that mummy fed them into it. Only thing was that we put multi meaning words in the end.
    "1":{"englishQ":"body","avestaAns":[["t","a","n","u"]]},
    "2":{"englishQ":"then","avestaAns":[["A","a","T"]]},
    "3":{"englishQ":"righteousness","avestaAns":[["a","C","a"]]},
    "4":{"englishQ":"Ahurem","avestaAns":[["a","h","u","r","v","m"]]},
    "5":{"englishQ":"Dātré","avestaAns":[["d","A","t","a","r","v"]]},
    "6":{"englishQ":"my","avestaAns":[["m","V"]]},
    "7":{"englishQ":"toe / finger","avestaAns":[["a","N","g","u","S","t","a"]]},
    "8":{"englishQ":"How many?","avestaAns":[["c","w","a","N","T"]]},
    "9":{"englishQ":"timely","avestaAns":[["r","a","q","B","y","a"]]},
    "10":{"englishQ":"best","avestaAns":[["W","a","h","i","S","t","a"]]},
    "11":{"englishQ":"dawn","avestaAns":[["u","C","a"]]},
    "12":{"englishQ":"blessed","avestaAns":[["a","‚","y","a"]]},
    "13":{"englishQ":"driving away","avestaAns":[["u","p","A","z","a","n","a"]]},
    "14":{"englishQ":"having healthy horses","avestaAns":[["d","r","a","w","A","s","p","a"]]},
    "15":{"englishQ":"healthy","avestaAns":[["d","r","a","w","a"]]},
    "16":{"englishQ":"horse","avestaAns":[["a","s","p","a"]]},
    "17":{"englishQ":"we gave","avestaAns":[["n","i","d","a","q","A","m","a"]]},
    "18":{"englishQ":"field","avestaAns":[["c","a","r","A","n","i"]]},
    "19":{"englishQ":"tree","avestaAns":[["W","a","n","&","m"]]},
    "20":{"englishQ":"I poured down.","avestaAns":[["n","I","r","e"]]},
    "21":{"englishQ":"good","avestaAns":[["h","u"]]},
    "22":{"englishQ":"word","avestaAns":[["u","x","t","a"]]},
    "23":{"englishQ":"good word","avestaAns":[["h","U","x","t","a"]]},
    "24":{"englishQ":"here","avestaAns":[["i","D","a"]]},
    "25":{"englishQ":"not here / neither","avestaAns":[["n","a","E","D","a"]]},
    "26":{"englishQ":"together","avestaAns":[["h","a","D","a"]]},
    "27":{"englishQ":"Hadokht (Nask)","avestaAns":[["h","a","D","a","o","x","t","a"]]},
    "28":{"englishQ":"to go towards","avestaAns":[["a","r"]]},
    "29":{"englishQ":"for Mazda","avestaAns":[["m","a","z","d","A","i"]]},
    "30":{"englishQ":"for Ahura","avestaAns":[["a","h","u","r","A","i"]]},
    "31":{"englishQ":"comes","avestaAns":[["A"]]},
    "32":{"englishQ":"comes towards","avestaAns":[["A","i","t","E"]]},
    "33":{"englishQ":"thus","avestaAns":[["u","i","t","i"]]},
    "34":{"englishQ":"speaking thus","avestaAns":[["u","i","t","y","a","o","j","a","n","a"]]},
    "35":{"englishQ":"against","avestaAns":[["p","a","i","t","i"]]},
    "36":{"englishQ":"opposition","avestaAns":[["p","a","i","t","y","A","r","a"]]},
    "37":{"englishQ":"Spityura","avestaAns":[["s","p","i","t","y","u","r","a"]]},
    "38":{"englishQ":"For the holy lady.","avestaAns":[["a","C","a","o","n","y","A","i"]]},
    "39":{"englishQ":"from the body","avestaAns":[["t","a","n","w","a","T"]]},
    "40":{"englishQ":"greatly beloved","avestaAns":[["h","w","A","f","r","i","t","a"]]},
    "41":{"englishQ":"wide","avestaAns":[["u","r","u"]]},
    "42":{"englishQ":"water","avestaAns":[["A","p","a"]]},
    "43":{"englishQ":"widely flowing water","avestaAns":[["u","r","w","A","p","a"]]},
    "44":{"englishQ":"very small","avestaAns":[["k","a","s","u"]]},
    "45":{"englishQ":"small","avestaAns":[["k","a","s","w","i"]]},
    "46":{"englishQ":"time","avestaAns":[["z","r","w","A","n","a"]]},
    "47":{"englishQ":"cow / bull","avestaAns":[["g","a","o"]]},
    "48":{"englishQ":"with the cow / bull","avestaAns":[["g","a","w","a"]]},
    "49":{"englishQ":"of the cow's / bull's","avestaAns":[["g","a","w","&","m"]]},
    "50":{"englishQ":"affliction","avestaAns":[["d","r","i","t","a"]]},
    "51":{"englishQ":"indeed / surely","avestaAns":[["z","I","T"]]},
    "52":{"englishQ":"speaking in accordance","avestaAns":[["a","n","U","x","t","a"]]},
    "53":{"englishQ":"approached","avestaAns":[["u","p","a","E","t","a"]]},
    "54":{"englishQ":"and the women","avestaAns":[["n","A","i","r","y","a","s","c","a"]]},
    "55":{"englishQ":"for the world","avestaAns":[["a","M","h","w","e"]]},
    "56":{"englishQ":"to be old","avestaAns":[["z","r","u"]]},
    "57":{"englishQ":"for Gathas","avestaAns":[["g","A","q","A","i"]]},
    "58":{"englishQ":"spoke forth","avestaAns":[["f","r","a","o","x","t","a"]]},
    "59":{"englishQ":"poured","avestaAns":[["i","r","i","x","t","a"]]},
    "60":{"englishQ":"divided / approportioned","avestaAns":[["b","a","x","t","a"]]},
    "61":{"englishQ":"dead","avestaAns":[["i","r","i","s","t","a"]]},
    "62":{"englishQ":"truth","avestaAns":[["r","A","s","t","i"]]},
    "63":{"englishQ":"offering","avestaAns":[["m","y","a","z","d","a"]]},
    "64":{"englishQ":"gift","avestaAns":[["d","a","z","d","a"]]},
    "65":{"englishQ":"we gave","avestaAns":[["n","i","d","a","q","A","m","a"]]},
    "66":{"englishQ":"to give / to know / to create","avestaAns":[["d","a","√-"]]},
    "67":{"englishQ":"to create","avestaAns":[["d","A","q","√-"]]},
    "68":{"englishQ":"angry","avestaAns":[["g","r","a","N","t","a"]]},
    "69":{"englishQ":"to venerate / to worship","avestaAns":[["Y","a","z","√-"]]},
    "70":{"englishQ":"venerated / attuned","avestaAns":[["Y","a","S","t","a"]]},
    "71":{"englishQ":"to ask","avestaAns":[["p","a","r","s","√-"]]},
    "72":{"englishQ":"asked / question","avestaAns":[["p","a","r","S","t","a"]]},
    "73":{"englishQ":"to be / is","avestaAns":[["a","h","√-"]]},
    "74":{"englishQ":"he is / she is / it is","avestaAns":[["a","s","t","i"]]},
    "75":{"englishQ":"to wear","avestaAns":[["W","a","h","√-"]]},
    "76":{"englishQ":"he wears / she wears","avestaAns":[["W","a","s","t","e"]]},
    "77":{"englishQ":"veneration","avestaAns":[["Y","a","s","n","a"]]},
    "78":{"englishQ":"arrangement","avestaAns":[["r","a","C","n","u"]]},
    "79":{"englishQ":"carrying","avestaAns":[["W","a","s","m","a"]]},
    "80":{"englishQ":"to die","avestaAns":[["m","a","r","√-"]]},
    "81":{"englishQ":"man","avestaAns":[["m","a","‚","y","a"]]},
    "82":{"englishQ":"Guardian Spirit / Fravashi","avestaAns":[["f","r","a","w","a","C","i"]]},
    "83":{"englishQ":"seed","avestaAns":[["t","a","x","m","a","n"]]},
    "84":{"englishQ":"to heat","avestaAns":[["t","a","p","√-"]]},
    "85":{"englishQ":"fever / heat","avestaAns":[["t","a","f","n","u"]]},
    "86":{"englishQ":"exhilaration","avestaAns":[["m","a","s","t","i"]]},
    "87":{"englishQ":"to think","avestaAns":[["c","i","T","√-"]]},
    "88":{"englishQ":"knowledge","avestaAns":[["c","i","s","t","i"]]},
    "89":{"englishQ":"vomited","avestaAns":[["W","a","N","t","a"]]},
    "90":{"englishQ":"rubbed","avestaAns":[["m","a","r","S","t","a"]]},
    "91":{"englishQ":"to wish / to desire / to throw","avestaAns":[["i","C","√-"]]},
    "92":{"englishQ":"to burn / to shine","avestaAns":[["u","C","√-"]]},
    "93":{"englishQ":"to do","avestaAns":[["k","vrv","√-"]]},
    "94":{"englishQ":"to rule / to shine","avestaAns":[["x","C","i","√-"]]},
    "95":{"englishQ":"to go","avestaAns":[["g","a","m","√-"]]},
    "96":{"englishQ":"to hear","avestaAns":[["g","u","C","√-"]]},
    "97":{"englishQ":"to tear","avestaAns":[["d","vrv","√-"]]},
    "98":{"englishQ":"to lie / to hurt / to decieve","avestaAns":[["d","r","u","j","√-"]]},
    "99":{"englishQ":"to protect","avestaAns":[["p","A","√-"]]},
    "100":{"englishQ":"country","avestaAns":[["d","a","F","y","u"],["d","a","i","?","h","u"]]},
    "101":{"englishQ":"mountain","avestaAns":[["g","a","i","r","i","S"],["b","a","r","v","z","a","M","h"]]},
    "102":{"englishQ":"pain","avestaAns":[["d","vrv"],["d","r","i","t","a"]]},
    "103":{"englishQ":"teaching","avestaAns":[["T","k","a","E","C","a"],["s","a","s","t","i"]]},
    "104":{"englishQ":"to go","avestaAns":[["g","a","m","√-"],["i","√-"],["a","r","√-"]]}
}